// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbvwkdefcydigovcsud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYnZ3a2RlZmN5ZGlnb3Zjc3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODQ3MDIsImV4cCI6MjA2NTM2MDcwMn0.eriRMv7stAq2JpliMceVgxs7kiFu1UjYdlFST-1-4Zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);